### ISSUE TITLE
ER図の作成

### ISSUE THREAD

**Issue by Gurrium** [kure-kosen/stock_intern_rails#3]

**Comment by Gurrium** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ER図の作成](https://trello.com/c/TP6L5bhg/28-er%E5%9B%B3%E3%81%AE%E4%BD%9C%E6%88%90)

**Comment by chanyou0311** [comment]
ER図の掲載お願いします

**Comment by Gurrium** [comment]
![img_5293](https://user-images.githubusercontent.com/13819100/31080494-c9caead6-a7c3-11e7-9621-d766228b0173.JPG)

**Comment by chanyou0311** [comment]
いいと思います！
