### ISSUE TITLE
記事ページのデザイン作成

### ISSUE THREAD

**Issue by chanyou0311** [kure-kosen/stock_intern_rails#4]

**Comment by chanyou0311** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [記事ページのデザイン作成](https://trello.com/c/2XkTlFGy/30-%E8%A8%98%E4%BA%8B%E3%83%9A%E3%83%BC%E3%82%B8%E3%81%AE%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E4%BD%9C%E6%88%90)

**Comment by chanyou0311** [comment]
![iphone 6](https://user-images.githubusercontent.com/12185831/31367924-6c89f98c-adb5-11e7-942f-47b20968a4b6.png)
![pc](https://user-images.githubusercontent.com/12185831/31367925-6cb55528-adb5-11e7-9493-8f69487f89d7.png)

**Comment by taira120** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [記事モデルの作成](https://trello.com/c/Y9F7b88g/37-%E8%A8%98%E4%BA%8B%E3%83%A2%E3%83%87%E3%83%AB%E3%81%AE%E4%BD%9C%E6%88%90)

**Comment by chanyou0311** [comment]
- もっと読むボタンの追加
- 行間が狭い
- 文字が小さい
- 先にモックアップ作るべきでは？
- いいね数
